apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-server
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: {{ .Values.global.nfs_server_path }}
    server: {{ .Values.global.nfs_server_ip }}
